return {
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-2477889104"]={
    configuration_options={
      COLOR_DOMESTICATION_DEFAULT="WHITE",
      COLOR_DOMESTICATION_ORNERY="ORANGE",
      COLOR_DOMESTICATION_PUDGY="PURPLE",
      COLOR_DOMESTICATION_RIDER="BLUE",
      COLOR_OBEDIENCE="RED",
      COLOR_TIMER="GREEN",
      EnableSounds=false,
      GapModifier=0,
      HungerThreshold=10,
      OffsetX=0,
      OffsetXFine=0,
      OffsetXMult=1,
      OffsetY=0,
      OffsetYFine=0,
      OffsetYMult=1,
      SEPARATOR_BADGE_COLORS=1,
      SEPARATOR_GENERAL=1,
      SEPARATOR_POSITIONING_X=1,
      SEPARATOR_POSITIONING_Y=1,
      Scale=1,
      ShowByDefault=true,
      Theme="TheForge",
      ToggleKey="KEY_T" 
    },
    enabled=true 
  },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="EN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-569043634"]={
    configuration_options={
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      NoPlayerSkeletons="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged" 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  } 
}